#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# galatea-fabrica-agentes.sh
# Role: Fábrica de agentes
# Version: 1.1
# Author: thdora-guardian[bot]
# FUNCIÓN ÚNICA: Genera agentes nuevos con plantilla unificada, cabecera y estructura estándar

NAME="${1:-}"
ROLE="${2:-}"
TYPE="${3:-auditor}"
OUT_DIR="scripts/agentes"
OUT="${OUT_DIR}/${NAME}.sh"

if [[ -z "$NAME" || -z "$ROLE" ]]; then
  echo "Usage: $0 \"nombre\" \"función\" \"tipo\""
  exit 1
fi

mkdir -p "$OUT_DIR"

cat > "$OUT" <<TEMPLATE
#!/usr/bin/env bash
set -euo pipefail
IFS=\$'\n\t'

# Agent: ${NAME}
# Role: ${ROLE}
# Type: ${TYPE}
# Version: 0.1
# Author: TODO
# FUNCIÓN ÚNICA: ${ROLE}
# Tags: autogenerated, agent

DRY_RUN=false
VERBOSE=false
OUT_DIR="\${OUT_DIR:-inbox/${NAME}}"

log(){ printf '%s %s\n' "\$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "\$*"; }
on_err(){ log "ERROR at line \$1"; exit 2; }
trap 'on_err \$LINENO' ERR

usage(){
  cat <<E
Usage: \$0 [--dry-run] [--verbose] [--out DIR]
E
  exit 1
}

while [[ "\${1:-}" != "" ]]; do
  case "\$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --verbose) VERBOSE=true; shift ;;
    --out) OUT_DIR="\$2"; shift 2 ;;
    -h|--help) usage ;;
    *) shift ;;
  esac
done

mkdir -p "\$OUT_DIR"

main(){
  log "Agent ${NAME} starting role=${ROLE} type=${TYPE}"
  # TODO: implement agent logic
  log "Agent ${NAME} finished"
}

main "\$@"
TEMPLATE

chmod +x "$OUT"
echo "Created $OUT"
